theme: jekyll-theme-slate
title: CS320 Experiment - CoW - Fall 2018
description: This is a user interface usability experiment. Participants are asked to work through each of the designs, and at the very end, click on the Google Forms link to fill out a survey.
